const alerts = [
  ["A01", "Missing reservation", "Reservation", "error", "Error", "An OT reaches its start without all required reels reserved.", "Warehouse cannot reliably prepare the correct material.", "The reservation was forgotten, incomplete, or created late.", "OT 151200.1 starts requiring four reels, but only three are reserved.", "Compare the OT's required materials with its reservation records at the configured pre-start deadline and actual start. Alert when required reservations are missing."],
  ["A02", "Material not dispatched", "Dispatch", "upcoming", "Por vencer, then Error", "Reserved reels have not been sent before the required pre-start time.", "The OT may start without material at the machine.", "Warehouse delay, missing dispatch action, or incorrect schedule.", "The OT starts at 10:00 and its reels remain in the warehouse at 09:30.", "Calculate planned start minus configured dispatch lead time. Show Por vencer before the cutoff and an error after the cutoff when any reserved reel lacks a dispatch event."],
  ["A03", "Material in transit too long", "Transit and receipt", "error", "Error", "A dispatched reel has not been digitally received within the permitted interval.", "The material's recorded location is uncertain.", "Operator forgot receipt, physical movement was delayed, or the destination was incorrect.", "A reel remains En tránsito for 38 minutes against a 30-minute limit.", "Find dispatched reels with no receipt event. Calculate current time minus dispatch time; alert when it exceeds the configured transit threshold."],
  ["A04", "OT started outside sequence", "Production sequence", "error", "Error", "An operator starts an OT that is not next in the latest approved machine sequence.", "Production is no longer following the supervisor's current plan.", "Operator selected the wrong OT or used an outdated sequence.", "P12 starts OT 151104.1 while OT 151099.1 is first in the approved sequence.", "At the actual start timestamp, compare the started OT with the first pending OT in the latest supervisor-approved sequence for that machine."],
  ["A05", "Active OT without consumption", "Consumption", "error", "Error", "An OT remains active beyond the allowed initial interval without any consumption declaration.", "Production cannot operate without raw material, so the digital workflow is incomplete.", "Operator forgot to declare consumption or started the OT too early.", "An OT has been active for 15 minutes with zero consumed reels.", "Require OT active, elapsed time since start greater than the configured interval, and consumption count equal to zero. Production declarations may support the same alert but must not create a duplicate."],
  ["A06", "Declared meters exceed consumed-reel meters", "OT closure", "error", "Error", "At closure, declared run meters materially exceed the estimated meters provided by consumed reels.", "The declared production cannot be explained by recorded consumption.", "Missing consumption declaration, incorrect run meters, incorrect reel data, or incorrect closure.", "Consumed reels support approximately 30,000 m, but the operator declares 40,000 m.", "Estimate meters in every consumed reel from weight, width, and basis weight. Sum them and compare them with declared run meters. Alert when the difference exceeds the configured tolerance. This is the primary closure rule."],
  ["A07", "Completed OT with delivered reserved reels unconsumed", "OT closure", "error", "Error", "An OT completes all planned production, but a reserved reel delivered to the machine remains unconsumed.", "If full production was completed, the delivered reserved material should have been used and declared.", "Missing consumption declaration, incorrect completion status, or incorrect reservation quantity.", "Four reels were reserved and delivered; full production was completed, but only three were consumed.", "Require full planned production completed, reserved reels delivered to the machine, and delivered reserved reels minus consumed reels is not empty. Do not apply automatically to truncated OTs."],
  ["A08", "Truncated OT", "OT closure", "notice", "Notice", "An OT closes before completing planned production or consuming all reserved material.", "The incomplete production must be understood, but truncation is not automatically an error.", "Machine failure, material problem, schedule change, or authorized early termination.", "An OT stops at 70% of the plan with one reserved reel unused.", "Show a review notice when the OT has a truncation or partial-completion status. Include the recorded reason, requester, approval, and remaining material."],
  ["A09", "Possible undeclared produced reel", "Production declaration", "possible", "Possible error", "Input mass exceeds what could physically remain on the rewinder without additional produced-reel declarations.", "One or more completed reels may have been removed without being declared.", "Operator forgot the declaration, declared it late, or the mass assumptions are inaccurate.", "The rewinder holds at most 500 kg, but 1,500 kg has been loaded without enough output declarations.", "Calculate unaccounted kg as input kg minus declared output kg minus declared waste kg minus allowed process loss. Warn when unaccounted kilograms exceed rewinder capacity plus tolerance. This is inferred because no PLC signal currently exists."],
  ["A10", "Produced reel not collected", "Pickup and movement", "error", "Error", "A declared reel remains at the machine beyond the permitted pickup interval.", "It can obstruct production and has not entered the weighing or downstream flow.", "Process-team delay, missing movement record, or incorrect location.", "A reel declared at P15 remains recorded there after 30 minutes.", "Start the timer at the production declaration. Alert when no pickup or movement event exists and the reel remains at the machine beyond the configured threshold."],
  ["A11", "Produced reel not weighed", "Weighing", "upcoming", "Por vencer, then Error", "A declared produced reel has no recorded weight within the permitted interval.", "Its inventory quantity and downstream usability remain incomplete.", "Pickup delay, scale queue, missed weighing, or missing digital record.", "A reel remains unweighed 34 minutes after its declaration.", "Find produced-reel records with unweighed status and no scale record. Use current time minus production declaration time; warn before the deadline and alert after it."],
  ["A12", "Waste bag not declared", "Waste declaration", "unsupported", "Unsupported hypothesis", "A physical waste bag is full and closed but has no declaration or barcode record.", "Waste and material balance become incomplete.", "Operator forgot the declaration or label.", "A closed waste bag remains beside the machine without a digital record.", "Current systems provide no independent signal proving that the physical bag exists. This cannot become a version 1 alert unless another reliable event is identified."],
  ["A13", "Declared waste bag not weighed", "Waste weighing", "error", "Error", "A digitally declared waste bag has not been weighed within the permitted interval.", "Waste quantity and OT reconciliation remain incomplete.", "Pickup delay, scale delay, or missed weighing.", "Waste bag MR-10982 was declared 34 minutes ago but has no weight.", "Start the timer at the waste declaration. Alert when no corresponding scale record exists after the configured threshold."],
  ["A14", "Incomplete reel used downstream", "Downstream movement", "possible", "Candidate error", "A produced reel is transferred to or consumed by another OT while required information, such as its weight, is missing.", "Incomplete data propagates into another production stage.", "Premature movement, missing weighing, or insufficient ERP validation.", "An unweighed printed reel is sent to lamination.", "When a downstream movement or consumption event occurs, verify that the source reel has all required fields and prior events. This remains a candidate until confirmed against ERP validations."]
];

const excluded = [
  ["Consumed reel was not reserved for the OT", "Impossible: EMUSA Soft prevents this consumption."],
  ["Production declared while an active OT has no consumption", "Duplicate: the active-OT-without-consumption alert already exists."],
  ["Rewinder completion detected directly", "No PLC or machine-completion signal currently exists."],
  ["Physical label was not printed", "Not observable without printer acknowledgment or print-job failure data."],
  ["Scale discovers an undeclared reel", "Useful as late reconciliation evidence, but too late to be the primary warning."]
];

document.querySelector("#catalog").innerHTML = alerts.map(([id, title, stage, state, status, when, why, causes, example, detection]) => `
  <article class="alert-card state-${state}" id="${id.toLowerCase()}" aria-labelledby="${id.toLowerCase()}-title">
    <div class="card-heading">
      <div><span class="alert-id">${id} · ${stage}</span><h2 id="${id.toLowerCase()}-title">${title}</h2></div>
      <span class="state-pill">${status}</span>
    </div>
    <div class="definition-grid">
      <section><h3>When it happens</h3><p>${when}</p></section>
      <section><h3>Why the alert exists</h3><p>${why}</p></section>
      <section><h3>Possible causes</h3><p>${causes}</p></section>
      <section><h3>Example</h3><p>${example}</p></section>
    </div>
    <section class="detection-rule"><span>Detection indicators and algorithm</span><p>${detection}</p></section>
  </article>
`).join("");

document.querySelector("#excluded-list").innerHTML = excluded.map(([rule, reason]) => `
  <section><strong>${rule}</strong><p>${reason}</p></section>
`).join("");

